title: "HANKIMKOR"
email: forhankyul@gmail.com
timezone: UTC
baseurl: ""
permalink: "/:title/"
logo: "assets/images/logo.png"
favicon: "assets/images/favicon.ico"
author: HANKIM
paginate: 30
disqus: "demowebsite"
languages: ["ko", "en"]
default_lang: "ko"
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    css_class: "highlight"
    span:
      line_numbers: false
    block:
      line_numbers: false
      start_line: 1
sass:
  sass_dir: _sass
  style: compressed
google_analytics: G-4G67JR7FJS

# Authors
authors:
  HANKIM:
    name: HANKIM
    display_name: HANKIM
    avatar: "assets/images/logo.png"
    email: forhankyul@gmail.com
    web: https://hankimkor.github.io
    description: "HELLO"

# Social
# social:
#   instagram: https://www.instagram.com/bootstrapstarter/
#   facebook: https://www.facebook.com/bootstrapstartercom-346329609045284
#   twitter: https://twitter.com/bstartercom

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives

defaults:
  - scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "post"
      lang: "ko"
  - scope:
      path: "_posts/*/*.en.md"
      type: "posts"
    values:
      layout: "post"
      lang: "en"
